name: Doxygen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Doxygen
        run: |
          sudo apt update
          sudo apt install -y doxygen
      - name: Build pages
        run: doxygen Doxyfile
